[package]
name = "fake_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.5", features = ["derive"]}
rand = "0.8"
url = "2.3.1"
thiserror = "1.0.38"